# Page settings

baseurl = "https://resume.witl.xyz/"
languageCode = "en-us"
title = "Tyler Witlin' Resume"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Tyler Witlin"
        tagline = ""
        avatar = "tyler.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//witl.xyz"
        title = "witl.xyz"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:tylerwitlin@gmail.com"
        title = "tylerwitlin@gmail.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/tyler-witlin"
        title = "linkedin.com/in/tyler-witlin"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/coolguy1771"
        title = "github.com/coolguy1771"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        college = "Arizona State University"
        major = "Computer Science (Cybersecurity)"
        dates = "2021 - 2025"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Gaming"
        [[params.interests.list]]
        interest = "Learning"
        [[params.interests.list]]
        interest = "Homelabbing"
        [[params.interests.list]]
        interest = "Music"
    # Skills section
    [params.rskill]
        enable = true
        title = "Skills & Proficiency"
        [[params.rskill.list]]
        skill = "Docker & Kubernetes"
        level = "%"
        [[params.rskill.list]]
        skill = "Linux"
        level = "%"
        [[params.rskill.list]]
        skill = "Automation Tooling"
        level = "%"
        [[params.rskill.list]]
        skill = "Git"
        level = "%"
        [[params.rskill.list]]
        skill = "Go"
        level = "%"
        [[params.rskill.list]]
        skill = "Java"
        level = "%"
        

# Main body sections
    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)
    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """As a Student learning Computer Science, I enjoy taking on new and interesting challenges to improve my own skills. I take pride in my work and am always trying to provide the best end result that I can.
        \nI am currently learning Automation Tooling (Ansible) and machine configuration using Terraform. I am also taking a specific focus on kubernetes and the automation, configuration, and management of clusters. Additonally, I also have experiance with troubleshooting hardware, software, and applications with most major operating systems and other major applications.
        \nI am always seeking new opportunities to develop cohesive systems for users and companies. 
        """

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Team Member"
        dates = "2020 - 2020"
        company = "Chipotle"
        details = "Team member preparing food orders for customers"


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"

        [[params.projects.list]]
        title = "Home Kubernetes Cluster"
        url = "https://github.com/coolguy1771/k3s"
        tagline = """Self deployed Kubernetes cluster at home based. Technologies used include:
        \n- Ansible & Terraform configurations to automate deoployment of the cluster
        \n- Renovate to create and merge pull requests
        \n- Grafana, Prometheus and Loki monitoring stack
        \n- Fluxcd 
        \nThe cluster was designed on GitOps principals and leverages automation techologies """


        

    # Location section
    [params.location]
        enable = false
        icon = "fa-globe"
        title = "Locations"

        [[params.location.list]]
        title = "Herndon, VA"
        tagline = "May 2003 - Current"
        [[params.location.list]]
        title = "Tempe, AZ"
        tagline = "August 2021 - Current"
    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ported for Tyler Witlin"
