# Cross compile the website docker container and push to Docker Hub
name: Cross Compile resume

on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # This is required in order to build ARM images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # This is required in order to cross-compile ARM images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Makes sure to log into Dockerhub
      - name: Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
